# Copyright (c) 2026 Varun Pratap Bhardwaj. All rights reserved.
# Licensed under MIT. See LICENSE file.
# Part of Qualixar — The Complete Agent Development Platform
"""Cryptographic output signing for Qualixar product provenance.

This module provides the ``QualixarSigner`` class which embeds cryptographic
provenance metadata into all tool outputs. Every JSON output (ASBOM, lockfile,
scan result) can carry a ``_qualixar`` block that allows verification of
authenticity and integrity.

The signing uses SHA-256 content hashing. In production deployments, this
can be upgraded to Ed25519 with a private key for non-repudiation.

Usage::

    from skillfortify.qualixar_attribution import QualixarSigner

    signer = QualixarSigner("skillfortify", "0.3.1")
    signed_output = signer.sign({"findings": [...], "score": 0.95})
    assert QualixarSigner.verify(signed_output)
"""

from __future__ import annotations

import hashlib
import json
import time
from typing import Any


class QualixarSigner:
    """Signs tool outputs with cryptographic provenance metadata.

    Each signed output receives a ``_qualixar`` block containing:
    - Tool identity and version
    - Platform attribution
    - SHA-256 content hash
    - Timestamp
    - HMAC-style signature (upgradeable to Ed25519)
    - Verification URL
    """

    TOOL_REGISTRY: dict[str, str] = {
        "agentassert": "AgentAssert — Behavioral Contracts",
        "agentassay": "AgentAssay — Stochastic Testing",
        "skillfortify": "SkillFortify — Security Validation",
        "superlocalmemory": "SuperLocalMemory — Agent Memory",
        "telephonebench": "TelephoneBench — Communication Benchmarks",
        "vibecheck": "VibeCheck — Code Reliability",
        "agentreplay": "AgentReplay — Time-Travel Debugging",
        "agentchaos": "AgentChaos — Chaos Engineering",
        "agentmigrate": "AgentMigrate — Migration Engineering",
        "agentpact": "AgentPact — Composition Testing",
    }

    def __init__(self, tool_name: str, version: str) -> None:
        self.tool_name = tool_name
        self.version = version
        self.tool_desc = self.TOOL_REGISTRY.get(tool_name, tool_name)

    def sign(self, output_data: Any) -> dict[str, Any]:
        """Add cryptographic provenance to any output.

        If ``output_data`` is a dict, the ``_qualixar`` block is merged in.
        Otherwise, the data is wrapped under a ``"data"`` key.

        Args:
            output_data: The tool output to sign. Typically a dict.

        Returns:
            A dict containing the original data plus a ``_qualixar`` block.
        """
        timestamp = time.time()
        canonical = json.dumps(output_data, sort_keys=True, default=str)
        content_hash = hashlib.sha256(canonical.encode()).hexdigest()

        provenance = {
            "_qualixar": {
                "tool": self.tool_name,
                "tool_description": self.tool_desc,
                "version": self.version,
                "platform": "Qualixar",
                "timestamp": timestamp,
                "content_hash": content_hash,
                "license": "MIT",
                "attribution": f"Generated by {self.tool_desc} v{self.version}",
                "verify": f"https://qualixar.com/verify/{content_hash[:16]}",
                "signature": self._compute_signature(content_hash, timestamp),
            }
        }

        if isinstance(output_data, dict):
            result = dict(output_data)
            result.update(provenance)
            return result
        return {"data": output_data, **provenance}

    def _compute_signature(self, content_hash: str, timestamp: float) -> str:
        """Compute HMAC-style signature over content hash and metadata.

        In production, replace with Ed25519 signing using a private key
        for non-repudiation guarantees.
        """
        sig_input = f"{self.tool_name}:{self.version}:{content_hash}:{timestamp}"
        return hashlib.sha256(sig_input.encode()).hexdigest()

    @staticmethod
    def verify(output_data: dict[str, Any]) -> bool:
        """Verify an output's provenance by recomputing the content hash.

        Strips the ``_qualixar`` block, recomputes SHA-256 over the remaining
        content, and compares with the stored ``content_hash``.

        Args:
            output_data: A dict that may contain a ``_qualixar`` provenance block.

        Returns:
            True if the content hash matches. False if missing or tampered.
        """
        prov = output_data.get("_qualixar", {})
        if not prov:
            return False
        content = {k: v for k, v in output_data.items() if k != "_qualixar"}
        canonical = json.dumps(content, sort_keys=True, default=str)
        expected_hash = hashlib.sha256(canonical.encode()).hexdigest()
        return prov.get("content_hash") == expected_hash

    def attribution_footer(self) -> str:
        """Return a human-readable attribution footer for text outputs.

        Suitable for appending to CLI output, text reports, or log files.
        """
        return (
            f"Generated by {self.tool_desc} v{self.version} | "
            f"Part of Qualixar | https://qualixar.com"
        )
